import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ShieldCheck,Link as LinkIcon,Image as ImageIcon,ScanLine,Mic,MessageSquare,ArrowRight,CheckCircle2,AlertTriangle,ShieldAlert,Lock,ChevronRight,RotateCcw} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_BASE || 'http://localhost:8000/api';
const modes=[['text','Paste Text',MessageSquare],['url','Check URL',LinkIcon],['image','Upload Image',ImageIcon],['qr','Scan QR',ScanLine],['audio','Upload Audio',Mic]];

function App(){
 const [mode,setMode]=useState('text'); const [text,setText]=useState(''); const [url,setUrl]=useState(''); const [file,setFile]=useState(null); const [context,setContext]=useState(''); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 async function analyze(){setLoading(true);setError('');setResult(null);try{let r;if(mode==='text')r=await fetch(API+'/analyze/text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,language:'auto'})});else if(mode==='url')r=await fetch(API+'/analyze/url',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,context})});else{const f=new FormData();f.append('file',file);f.append('context',context);r=await fetch(API+`/analyze/${mode==='qr'?'qr':mode}`,{method:'POST',body:f})}if(!r.ok)throw new Error('Analysis service returned an error');setResult(await r.json())}catch(e){setError('Could not reach the VERITAS analysis service. Start the FastAPI backend on port 8000.')}finally{setLoading(false)}}
 return <div className="app"><header><div className="brand"><div className="logo"><ShieldCheck/></div><div><div className="name">VERITAS</div><div className="tag">Digital Trust & Safety</div></div></div><div className="header-right"><span><Lock size={14}/> Privacy-first analysis</span><a className="ghost" href={API.replace('/api','')+'/docs'} target="_blank" rel="noreferrer">API Docs</a></div></header>
 <main><section className="hero"><div className="eyebrow">UNDERSTAND · VERIFY · TRUST</div><h1>What would you like<br/><span>to verify?</span></h1><p>Analyze suspicious messages, links and digital evidence before you click, pay, respond or trust.</p></section>
 <section className="workspace"><div className="tabs">{modes.map(([id,label,Icon])=><button key={id} className={mode===id?'tab active':'tab'} onClick={()=>{setMode(id);setResult(null)}}><Icon size={18}/>{label}</button>)}</div>
 <div className="panel">{mode==='text'&&<><label>Paste the message, email, or suspicious content</label><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Example: URGENT! Your account will be suspended today. Verify immediately using this link..."/><div className="helper">VERITAS checks urgency, financial requests, credential requests, impersonation signals and linked destinations.</div></>}
 {mode==='url'&&<><label>Suspicious URL</label><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/verify"/><label className="sub">Optional surrounding message</label><textarea value={context} onChange={e=>setContext(e.target.value)} placeholder="Paste the message that contained the link..."/></>}
 {(mode==='image'||mode==='qr'||mode==='audio')&&<><label>{mode==='qr'?'Upload a QR image':mode==='audio'?'Upload a voice note':'Upload a screenshot or image'}</label><div className="drop"><input type="file" accept={mode==='audio'?'audio/*':'image/*'} onChange={e=>setFile(e.target.files?.[0])}/><div className="drop-icon">{mode==='audio'?<Mic/>:mode==='qr'?<ScanLine/>:<ImageIcon/>}</div><strong>{file?file.name:'Choose a file'}</strong><span>or drag and drop</span></div><label className="sub">Optional context</label><textarea value={context} onChange={e=>setContext(e.target.value)} placeholder="What does the sender claim this is about?"/></>}
 <button className="analyze" disabled={loading || (mode==='text'&&!text.trim()) || (mode==='url'&&!url.trim()) || (mode!=='text'&&mode!=='url'&&!file)} onClick={analyze}>{loading?'Analyzing…':'ANALYZE'}<ArrowRight size={19}/></button>
 {error&&<div className="error">{error}</div>}</div></section>
 {result&&<Result data={result} onReset={()=>setResult(null)}/>} 
 <section className="principles"><div><ShieldCheck/><h3>Evidence, not guesswork</h3><p>Results explain the signals behind an assessment instead of simply labeling content “scam.”</p></div><div><Lock/><h3>Privacy by design</h3><p>User-controlled uploads, minimal collection and clear processing boundaries.</p></div><div><CheckCircle2/><h3>Safer next action</h3><p>Every assessment ends with a practical verification step.</p></div></section>
 </main><footer><span>VERITAS · Digital Trust & Safety Platform</span><span>Assessment is decision support, not absolute proof.</span></footer></div>
}
function Result({data,onReset}){const A=data.assessment;const Icon=A.color==='red'?ShieldAlert:A.color==='yellow'?AlertTriangle:CheckCircle2;return <section className="result"><div className="result-head"><div><div className="eyebrow">VERITAS ASSESSMENT</div><div className="risk"><Icon size={28}/><h2>{A.level}</h2></div><p>{data.summary}</p></div><div className={'score '+A.color}>{A.score}<small>/100</small></div></div><div className="grid"><div className="card"><h3>Why was this flagged?</h3>{data.evidence.length?data.evidence.map((e,i)=><div className="evidence" key={i}><div className="dot">✓</div><div><strong>{e.title}</strong><p>{e.detail}</p></div></div>):<p>No major warning signals were identified by this MVP analyzer.</p>}</div><div className="card action"><h3>Recommended Action</h3><div className="action-box"><ArrowRight/><p>{data.recommended_action}</p></div><div className="disclaimer">{data.disclaimer}</div><h4>How to verify safely</h4><ol className="steps">{data.verification_steps?.map((step,i)=><li key={i}>{step}</li>)}</ol></div></div><button className="reset" onClick={onReset}><RotateCcw size={16}/> Analyze something else</button></section>}
createRoot(document.getElementById('root')).render(<App/>);
